### ISSUE TITLE
Exercise 3 (CSS Form)

### ISSUE THREAD

**Issue by wilsonokibe** [wilsonokibe/CSS#2]
Exercise3: (Css Form)Create a CSS form layout using div's UL, LI etc.Layout design is here:http://dl.dropbox.com/u/17934144/vtapp/exercise3.jpgAnd here is VinSol Logo image:http://dl.dropbox.com/u/17934144/vtapp/vinsol-logo.png

URL:
https://github.com/wilsonokibe/CSS.git

**Comment by segunadeleye** [comment]
1. You are to use the `form` tag, not `div`. It is a form.
   https://github.com/wilsonokibe/CSS/blob/master/exercise3/exercise3.html#L16
2. When a style is defined for a parent, you don't need to define it for the children except you want to change the value. Let this be for the parent only. Every descendant then inherits the style.
   https://github.com/wilsonokibe/CSS/blob/master/exercise3/exercise3.html#L35
3. The `margin` styles are not needed. The second `20px` is not needed either.
   https://github.com/wilsonokibe/CSS/blob/master/exercise3/exercise3.css#L40
4. An `input` is inline by default. This is not needed.
   https://github.com/wilsonokibe/CSS/blob/master/exercise3/exercise3.css#L104
5. Use the default. You can remove it.
   https://github.com/wilsonokibe/CSS/blob/master/exercise3/exercise3.css#L122
6. Always remove commented styles.

**Comment by segunadeleye** [comment]
Good.
