### ISSUE TITLE
CSS Exercise 1

### ISSUE THREAD

**Issue by wilsonokibe** [wilsonokibe/CSS#3]
Exercise 1Create CSS based drop-downs menus like in given image below:Click on link to find the image:http://dl.dropbox.com/u/17934144/vtapp/exercise1.jpg

URL:
https://github.com/wilsonokibe/CSS/tree/master/exercise1

**Comment by wilsonokibe** [comment]
Exercise 1Create CSS based drop-downs menus like in given image below:Click on link to find the image:http://dl.dropbox.com/u/17934144/vtapp/exercise1.jpg

URL:
https://github.com/wilsonokibe/CSS.git

Updating Task 1

**Comment by wilsonokibe** [comment]
Minimized CSS

**Comment by segunadeleye** [comment]
1. Use the short form for this
   https://github.com/wilsonokibe/CSS/blob/master/exercise1/ex1.css#L35
   https://github.com/wilsonokibe/CSS/blob/master/exercise1/ex1.css#L36
2. Remove `color: black`
   https://github.com/wilsonokibe/CSS/blob/master/exercise1/ex1.css#L37
3. Remove commented styles.
4. Remove the `box-sizing` style in `.menu > li:hover`. It is not needed
5. We don't need this; `.menu:after`
   https://github.com/wilsonokibe/CSS/blob/master/exercise1/ex1.css#L64

**Comment by segunadeleye** [comment]
Looks fine.
